<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise 함수</title>
</head>
<body>
    <script>
    function increaseAndPrint(n) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            const value = n + 1;
            if (value === 5) {
                const error = new Error();
                error.name = 'ValueIsFiveError';
                reject(error);
                return;
            }
            console.log(value);
            resolve(value);
        }, 1000);
    });
    }

    increaseAndPrint(0)
    .then((n) => {
        return increaseAndPrint(n);
    })
    .then((n) => {
        return increaseAndPrint(n);
    })
    .then((n) => {
        return increaseAndPrint(n);
    })
    .then((n) => {
        return increaseAndPrint(n);
    })
    .then((n) => {
        return increaseAndPrint(n);
    })
    .catch(e => {
        console.log("error 발생해서 처리해줄 catch 부분 !! ");
        console.error(e);
    });


    /*
        then 내부에 넣은 함수에서 또 Promise를 리턴하면, 연달아서 사용가능하다!
    */
    </script>
</body>
</html>